# Generated by Django 4.0.6 on 2022-08-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.member'),
        ),
        migrations.AddField(
            model_name='slot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.court'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
        migrations.AddField(
            model_name='court',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
    ]
