# Generated by Django 4.0.6 on 2022-09-01 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sports', '0003_alter_equipment_quantity_alter_sport_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 1)),
        ),
        migrations.AddField(
            model_name='slot',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.member')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sports.slot')),
            ],
        ),
    ]
