# Generated by Django 4.0.6 on 2022-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='img_url',
            field=models.CharField(default='https://uploads-ssl.webflow.com/617b224ba2374548fcc039ba/617b224ba237453ce1c0409b_hpfulq-1234-1024x512.jpg', max_length=2083, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(help_text='Please, use underscores in place of spaces.', max_length=20, unique=True),
        ),
    ]
