# Generated by Django 4.0.6 on 2022-09-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_booking_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(help_text='(Time should be of format HH:MM from 00:00 to 23:59.)'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(help_text='(Time should be of format HH:MM from 00:00 to 23:59.)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(help_text='(Please, use underscore(_) or hypen(-) in place of spaces.)', max_length=20, unique=True),
        ),
    ]
