# Generated by Django 4.0.6 on 2022-09-03 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_alter_sport_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 3), help_text='(Date should be of format YYYY-MM-DD)'),
        ),
    ]
